#!/bin/bash

printf '\n\n\n'
/usr/lib/colorgcc/bin/g++ -std=c++0x -o sim -ggdb -Wall -Wextra -Wno-unknown-pragmas -O0 -fmax-errors=15 \
	-I/usr/include/SDL/ -I../boostbcp/ -lboost_system -lSDL -lGL -lGLU -lGLEW -lgmpxx -lgmp \
	*.cpp "$@"
